[package]
name = "shared_buffer_rust"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Rust RAII bindings for the shared_buffer ROS 2 backend"
repository = "https://github.com/dskkato/memfd_buffer_backend"
build = "build.rs"

[lib]
name = "shared_buffer_rust"
path = "src/lib.rs"

[package.metadata.ros]
install_to_share = ["package.xml"]
