name: ROS 2 Rolling CI

on:
  pull_request:
    branches:
      - rolling
  workflow_dispatch:

jobs:
  # build-and-test:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: rostooling/setup-ros-docker:ubuntu-resolute-ros-rolling-ros-base-latest

  #   steps:
  #     - name: Build and test ROS packages
  #       uses: ros-tooling/action-ros-ci@v0.4
  #       with:
  #         package-name: |
  #           memfd_buffer_backend_msgs
  #           memfd_buffer
  #           memfd_buffer_backend_py
  #           memfd_buffer_backend
  #         target-ros2-distro: rolling
  #         no-symlink-install: true
  #         colcon-defaults: |
  #           {
  #             "build": {
  #               "cmake-args": [
  #                 "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON"
  #               ]
  #             }
  #           }
  #         coverage-result: false

  windows-build-and-test:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
        with:
          path: src/memfd_buffer_backend

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.10.1
        with:
          manifest-path: src/memfd_buffer_backend/pixi.toml

      - name: Download ROS 2 Lyrical
        shell: pwsh
        run: |
          $url = "https://github.com/ros2/ros2/releases/download/release-lyrical-20260807/ros2-lyrical-2026-08-07-windows-AMD64.zip"

          Invoke-WebRequest $url -OutFile lyrical.zip
          Expand-Archive lyrical.zip -DestinationPath C:\dev\lyrical

      - name: Build
        shell: cmd
        run: |
          call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          call C:\dev\lyrical\ros2-windows\setup.bat
          pixi run colcon build --merge-install

      - name: Test
        shell: cmd
        run: |
          call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          call C:\dev\lyrical\ros2-windows\setup.bat
          call install\setup.bat
          pixi run colcon test --merge-install
          pixi run colcon test-result --verbose